# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1b7322059740430a13f30755cbbc42242957b163d3bd9f0d7a91e48444056afcb4aff49b38a07bd9e51c5b56c62b17eb18fcd1afe2a5a34fcbc4bf8944454b5

test:
  secret_key_base: 19666ea606641485b79bb3bb3a7bbe5ecc2e0839779b49a6681c6d344d1b123316b82c6fb04eb23712839d70aaa70904d363568e22674720bc3b6335bc4c5d79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
